name: 01 - Buidin Blocks
on: push 
jobs:
  echo-hello:
    runs-on: ubuntu-latest
    steps: 
      - name: Say hello
        run: echo "hello"
  echo-godbaye:
    runs-on:  ubuntu-latest
    steps:
      - name: FaILED STEP
        run: | #Usado para script de multiplas linhas
          echo "Will fail" 
          exit 1
      - name: Say goodbaye
       run: echo "Goodbaye"
